minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
neo_version=21.11.45
moddev_version=2.0.144
java_version=21
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
metadata_format=modern
command_api=legacy
