minecraft_version=1.21.8
minecraft_version_range=[1.21.8]
neo_version=21.8.54
moddev_version=2.0.144
java_version=21
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.09.14
metadata_format=modern
command_api=legacy
